name: xeus-r
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - make
  - cmake
  - cxx-compiler
  - ninja
  # Host dependencies
  - xeus>=5.0.0
  - xeus-zmq>=3.0,<4.0
  - nlohmann_json=3.11.3
  - r-base =4.3.1
  # Run dependencies
  - r-rlang
  - r-evaluate
  - r-jsonlite
  - r-glue
  - r-cli
  - r-repr
  - r-IRdisplay
  # Test dependencies
  - pytest
  - jupyter_kernel_test>=0.5,<0.6
  - nbval
  - pytest-rerunfailures
  - r-ggplot2
