name: xeus-r-wasm-build
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  # Xeus-R
  - cmake
  - pkg-config
  - emscripten_emscripten-wasm32==3.1.45
  # Hera
  - r-base
  - r-rlang
  - r-jsonlite
  - r-base64enc
  - r-digest
  # JupyterLite
  - jupyterlite-core
  - jupyter_server
  - jupyterlite-xeus
